// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: proto/minivault/v1/vault.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetSecretRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is the key to look up in the secrets map (e.g. "kek", "db_password").
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSecretRequest) Reset() {
	*x = GetSecretRequest{}
	mi := &file_proto_minivault_v1_vault_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecretRequest) ProtoMessage() {}

func (x *GetSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_minivault_v1_vault_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSecretRequest.ProtoReflect.Descriptor instead.
func (*GetSecretRequest) Descriptor() ([]byte, []int) {
	return file_proto_minivault_v1_vault_proto_rawDescGZIP(), []int{0}
}

func (x *GetSecretRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetSecretResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// value is the raw secret value bytes. Never logged.
	Value []byte `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	// name echoes back the requested key name.
	Name          string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSecretResponse) Reset() {
	*x = GetSecretResponse{}
	mi := &file_proto_minivault_v1_vault_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecretResponse) ProtoMessage() {}

func (x *GetSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_minivault_v1_vault_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSecretResponse.ProtoReflect.Descriptor instead.
func (*GetSecretResponse) Descriptor() ([]byte, []int) {
	return file_proto_minivault_v1_vault_proto_rawDescGZIP(), []int{1}
}

func (x *GetSecretResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *GetSecretResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_proto_minivault_v1_vault_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_minivault_v1_vault_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_proto_minivault_v1_vault_proto_rawDescGZIP(), []int{2}
}

type HealthCheckResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// loaded is true when secrets have been successfully decrypted and are in memory.
	Loaded bool `protobuf:"varint,1,opt,name=loaded,proto3" json:"loaded,omitempty"`
	// count is the number of secrets currently loaded.
	Count         int32 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_proto_minivault_v1_vault_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_minivault_v1_vault_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_proto_minivault_v1_vault_proto_rawDescGZIP(), []int{3}
}

func (x *HealthCheckResponse) GetLoaded() bool {
	if x != nil {
		return x.Loaded
	}
	return false
}

func (x *HealthCheckResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_proto_minivault_v1_vault_proto protoreflect.FileDescriptor

const file_proto_minivault_v1_vault_proto_rawDesc = "" +
	"\n\x1eproto/minivault/v1/vault.proto\x12\fminivault.v1\"&\n\x10GetSecretRequest\x12\x12\n\x04name\x18\x01 \x01(\tR\x04name\"=\n\x11GetSecretResponse\x12\x14\n\x05value\x18\x01 \x01(\fR\x05value\x12\x12\n\x04name\x18\x02 \x01(\tR\x04name\"\x14\n\x12HealthCheckRequest\"C\n\x13HealthCheckResponse\x12\x16\n\x06loaded\x18\x01 \x01(\bR\x06loaded\x12\x14\n\x05count\x18\x02 \x01(\x05R\x05count2\xb0\x01\n\fVaultService\x12L\n\tGetSecret\x12\x1e.minivault.v1.GetSecretRequest\x1a\x1f.minivault.v1.GetSecretResponse\x12R\n\vHealthCheck\x12 .minivault.v1.HealthCheckRequest\x1a!.minivault.v1.HealthCheckResponseB2Z0github.com/yourorg/mini-vault/proto/minivault/v1b\x06proto3"

var (
	file_proto_minivault_v1_vault_proto_rawDescOnce sync.Once
	file_proto_minivault_v1_vault_proto_rawDescData []byte
)

func file_proto_minivault_v1_vault_proto_rawDescGZIP() []byte {
	file_proto_minivault_v1_vault_proto_rawDescOnce.Do(func() {
		file_proto_minivault_v1_vault_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_minivault_v1_vault_proto_rawDesc), len(file_proto_minivault_v1_vault_proto_rawDesc)))
	})
	return file_proto_minivault_v1_vault_proto_rawDescData
}

var file_proto_minivault_v1_vault_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_minivault_v1_vault_proto_goTypes = []any{
	(*GetSecretRequest)(nil),    // 0: minivault.v1.GetSecretRequest
	(*GetSecretResponse)(nil),   // 1: minivault.v1.GetSecretResponse
	(*HealthCheckRequest)(nil),  // 2: minivault.v1.HealthCheckRequest
	(*HealthCheckResponse)(nil), // 3: minivault.v1.HealthCheckResponse
}
var file_proto_minivault_v1_vault_proto_depIdxs = []int32{
	0, // 0: minivault.v1.VaultService.GetSecret:input_type -> minivault.v1.GetSecretRequest
	2, // 1: minivault.v1.VaultService.HealthCheck:input_type -> minivault.v1.HealthCheckRequest
	1, // 2: minivault.v1.VaultService.GetSecret:output_type -> minivault.v1.GetSecretResponse
	3, // 3: minivault.v1.VaultService.HealthCheck:output_type -> minivault.v1.HealthCheckResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_minivault_v1_vault_proto_init() }
func file_proto_minivault_v1_vault_proto_init() {
	if File_proto_minivault_v1_vault_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeFor[x]().PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_minivault_v1_vault_proto_rawDesc), len(file_proto_minivault_v1_vault_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_minivault_v1_vault_proto_goTypes,
		DependencyIndexes: file_proto_minivault_v1_vault_proto_depIdxs,
		MessageInfos:      file_proto_minivault_v1_vault_proto_msgTypes,
	}.Build()
	File_proto_minivault_v1_vault_proto = out.File
	file_proto_minivault_v1_vault_proto_goTypes = nil
	file_proto_minivault_v1_vault_proto_depIdxs = nil
}
