// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: proto/minivault/v1/vault.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetKEKRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// version specifies which KEK version is requested.
	// Must match the version embedded in the binary.
	Version       string `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKEKRequest) Reset() {
	*x = GetKEKRequest{}
	mi := &file_proto_minivault_v1_vault_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKEKRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKEKRequest) ProtoMessage() {}

func (x *GetKEKRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_minivault_v1_vault_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKEKRequest.ProtoReflect.Descriptor instead.
func (*GetKEKRequest) Descriptor() ([]byte, []int) {
	return file_proto_minivault_v1_vault_proto_rawDescGZIP(), []int{0}
}

func (x *GetKEKRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type GetKEKResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// kek is the 32-byte raw Key Encryption Key.
	// Transmitted only over mTLS; never logged.
	Kek []byte `protobuf:"bytes,1,opt,name=kek,proto3" json:"kek,omitempty"`
	// version identifies this KEK (e.g. "v1").
	Version       string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKEKResponse) Reset() {
	*x = GetKEKResponse{}
	mi := &file_proto_minivault_v1_vault_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKEKResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKEKResponse) ProtoMessage() {}

func (x *GetKEKResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_minivault_v1_vault_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKEKResponse.ProtoReflect.Descriptor instead.
func (*GetKEKResponse) Descriptor() ([]byte, []int) {
	return file_proto_minivault_v1_vault_proto_rawDescGZIP(), []int{1}
}

func (x *GetKEKResponse) GetKek() []byte {
	if x != nil {
		return x.Kek
	}
	return nil
}

func (x *GetKEKResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_proto_minivault_v1_vault_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_minivault_v1_vault_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_proto_minivault_v1_vault_proto_rawDescGZIP(), []int{2}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KekLoaded     bool                   `protobuf:"varint,1,opt,name=kek_loaded,json=kekLoaded,proto3" json:"kek_loaded,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_proto_minivault_v1_vault_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_minivault_v1_vault_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_proto_minivault_v1_vault_proto_rawDescGZIP(), []int{3}
}

func (x *HealthCheckResponse) GetKekLoaded() bool {
	if x != nil {
		return x.KekLoaded
	}
	return false
}

func (x *HealthCheckResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

var File_proto_minivault_v1_vault_proto protoreflect.FileDescriptor

const file_proto_minivault_v1_vault_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/minivault/v1/vault.proto\x12\fminivault.v1\")\n" +
	"\rGetKEKRequest\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\"<\n" +
	"\x0eGetKEKResponse\x12\x10\n" +
	"\x03kek\x18\x01 \x01(\fR\x03kek\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"\x14\n" +
	"\x12HealthCheckRequest\"N\n" +
	"\x13HealthCheckResponse\x12\x1d\n" +
	"\n" +
	"kek_loaded\x18\x01 \x01(\bR\tkekLoaded\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion2\xa7\x01\n" +
	"\fVaultService\x12C\n" +
	"\x06GetKEK\x12\x1b.minivault.v1.GetKEKRequest\x1a\x1c.minivault.v1.GetKEKResponse\x12R\n" +
	"\vHealthCheck\x12 .minivault.v1.HealthCheckRequest\x1a!.minivault.v1.HealthCheckResponseB2Z0github.com/yourorg/mini-vault/proto/minivault/v1b\x06proto3"

var (
	file_proto_minivault_v1_vault_proto_rawDescOnce sync.Once
	file_proto_minivault_v1_vault_proto_rawDescData []byte
)

func file_proto_minivault_v1_vault_proto_rawDescGZIP() []byte {
	file_proto_minivault_v1_vault_proto_rawDescOnce.Do(func() {
		file_proto_minivault_v1_vault_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_minivault_v1_vault_proto_rawDesc), len(file_proto_minivault_v1_vault_proto_rawDesc)))
	})
	return file_proto_minivault_v1_vault_proto_rawDescData
}

var file_proto_minivault_v1_vault_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_minivault_v1_vault_proto_goTypes = []any{
	(*GetKEKRequest)(nil),       // 0: minivault.v1.GetKEKRequest
	(*GetKEKResponse)(nil),      // 1: minivault.v1.GetKEKResponse
	(*HealthCheckRequest)(nil),  // 2: minivault.v1.HealthCheckRequest
	(*HealthCheckResponse)(nil), // 3: minivault.v1.HealthCheckResponse
}
var file_proto_minivault_v1_vault_proto_depIdxs = []int32{
	0, // 0: minivault.v1.VaultService.GetKEK:input_type -> minivault.v1.GetKEKRequest
	2, // 1: minivault.v1.VaultService.HealthCheck:input_type -> minivault.v1.HealthCheckRequest
	1, // 2: minivault.v1.VaultService.GetKEK:output_type -> minivault.v1.GetKEKResponse
	3, // 3: minivault.v1.VaultService.HealthCheck:output_type -> minivault.v1.HealthCheckResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_minivault_v1_vault_proto_init() }
func file_proto_minivault_v1_vault_proto_init() {
	if File_proto_minivault_v1_vault_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_minivault_v1_vault_proto_rawDesc), len(file_proto_minivault_v1_vault_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_minivault_v1_vault_proto_goTypes,
		DependencyIndexes: file_proto_minivault_v1_vault_proto_depIdxs,
		MessageInfos:      file_proto_minivault_v1_vault_proto_msgTypes,
	}.Build()
	File_proto_minivault_v1_vault_proto = out.File
	file_proto_minivault_v1_vault_proto_goTypes = nil
	file_proto_minivault_v1_vault_proto_depIdxs = nil
}
